### PR TITLE
feat: add finalized: boolean to monetizationstop event

### PR DESCRIPTION
**Pull request by sublimator**
### monetizationstop finalized property

Related to https://github.com/interledger/webmonetization.org/issues/39

Allows determining when a "monetization" (that which is identified by a requestId) has completely finished without resorting to [looking at the document](https://github.com/sharafian/react-web-monetization/blob/8a86b37b237c18f461bdaa5d41caa6fa841ecbd3/src/global.js#L95-L99) . 

Due to the fact that we always create a new `requestId` for any "new" meta tag we can be sure that no more events will be emitted for a given requestId when we set `"finalized": true`.  We don't track unique payment pointers per page load, so if you removed a meta tag with paymentPointer $a, then added a meta tag back with $a, then a new requestId would be created. Generally that would make sense in that the request would likely be for different content.

### Current usages of finalized: false

The main "use" of finalized: false (i.e. paused) currently is when a page is backgrounded and goes into the stopped state. When the page is foregrounded again, the stream is resumed using the same requestId.

### Specification of dynamic/multiple monetization tags
We may want to specify the relation of a requestId to meta tags more precisely.
#### Important
See #41 

### Note on finalized term
Not stuck on `finalized`. @sharafian suggested an inverted property like 'temporary' may be better but agreed `finalized` is a good starting point for discussion.

### CODE REVIEW

**Comment by sublimator** [comment]
Well I won’t argue for it :)

**Comment by sublimator** [comment]
@melissahenderson 
> I'm not sure if it's really necessary/helpful.
Wasn't sure if you meant the field or adding to examples ? 
I just added the field to the example event object, with `finalized: false`

**Comment by matdehaast** [comment]
@sublimator does this mean if I get a `monetizationstop` without the `finalised` field it is essentially just a temp pause?

**Comment by sublimator** [comment]
@matdehaast 
Yeah, it's essentially a monetizationpaused event when finalized: false  (it won't be omitted, rather set to false)

**Comment by sharafian** [comment]
Is this added to WM projects' master branch? once it gets into an extension release we should merge this

**Comment by sublimator** [comment]
@sharafian this is in the 0.0.44 release

**Comment by sublimator** [comment]
once it gets into an extension release we should merge this
^

**Pull request merged**
